language: generic

matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:5.1.1
      script:
        - docker run -v "$(pwd):/root/aws-cognito-authentication" swift:5.1.1 /bin/sh -c "apt-get -qq update && apt-get -q -y install tzdata libssl-dev zlib1g-dev && cd /root/aws-cognito-authentication && swift build && swift test --parallel -Xswiftc -DDEBUG"
    - os: osx
      language: swift
      osx_image: xcode11
      script:
        - brew install libressl
        - swift build
        - swift test --parallel -Xswiftc -DDEBUG
