language: generic

matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:4.2
      script:
        - docker run -v "$(pwd):/root/aws-cognito-authentication" swift:4.2 /bin/sh -c "apt install libssl-dev && cd /root/aws-cognito-authentication && swift build && swift test --parallel -Xswiftc -DDEBUG"
    - os: osx
      language: swift
      osx_image: xcode10.2
      script:
        - swift build
        - swift test --parallel -Xswiftc -DDEBUG
