name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Test
      run: swift test

  linux:
    strategy:
      matrix:
        image: ["swift:5.2", "swift:5.3"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
