name: CI

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  macOS:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
    - name: Test
      run: swift test

  ios:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Xcodebuild
      run: |
        xcodebuild -scheme aws-cognito-authentication-kit-Package -quiet -destination 'platform=iOS Simulator,name=iPhone 11'
        xcodebuild test -scheme aws-cognito-authentication-kit-Package -destination 'platform=iOS Simulator,name=iPhone 11'

  linux:
    strategy:
      matrix:
        image: ["swift:5.2", "swift:5.3"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Build
      run: swift build
    - name: Test
      run: swift test
